### ISSUE TITLE
T4.1	Design the login page

### ISSUE THREAD

**Issue by piushan1992** [BlacklampsSE2/Game-Simulator#16]

**Comment by MadumalEkanayake** [comment]
![loginscreen](https://user-images.githubusercontent.com/28650587/40889265-4d0754ac-6781-11e8-91a7-15dbf8974bb8.jpg)
Rough design to the login screen.
After login user is to navigate to screen where main menu exist.

**Comment by Ruvimal1997** [comment]
I designed the login page according to the sketch. 
![capture](https://user-images.githubusercontent.com/13659894/40889291-b942d272-6781-11e8-91e6-9fe0127265e3.PNG)
