### ISSUE TITLE
T5.1	Design the UI to show this information

### ISSUE THREAD

**Issue by piushan1992** [BlacklampsSE2/Game-Simulator#20]

**Comment by MadumalEkanayake** [comment]
![20180603_220636](https://user-images.githubusercontent.com/28650587/40889315-215c8bb4-6782-11e8-8161-25b650b7fefe.jpg)

Main menu at the  right top of the screen. By clicking each respective page will slide up.

**Comment by Ruvimal1997** [comment]
I designed a one page with several pages as in your sketch
![capture](https://user-images.githubusercontent.com/13659894/40889340-94b32bc2-6782-11e8-8702-cead548ba163.PNG)
