### ISSUE TITLE
T13.4 Design the UI accordingly

### ISSUE THREAD

**Issue by piushan1992** [BlacklampsSE2/Game-Simulator#28]

**Comment by MadumalEkanayake** [comment]
![gameboard](https://user-images.githubusercontent.com/28650587/40889364-fc0c8ea8-6782-11e8-974e-a3c83102a51e.jpg)
Under Share details are the components to play the game.
News feed display rumors.
Inside portfolio bank balance and further details will display.

**Comment by Ruvimal1997** [comment]
And also the time is also displayed. I designed a web page for the above sketch
