### ISSUE TITLE
T16.1 Storyboard a UI to show this information

### ISSUE THREAD

**Issue by piushan1992** [BlacklampsSE2/Game-Simulator#37]

**Comment by MadumalEkanayake** [comment]
![gameboard](https://user-images.githubusercontent.com/28650587/40889443-68f55b5c-6784-11e8-8c32-32eed3d26b42.jpg)
Clock shows game time and number of turns for the game and how much have passed.

**Comment by Ruvimal1997** [comment]
I have designed the UI accordingly which will show the user no. of turns left and how much have been passed
