### ISSUE TITLE
T17.4 Implement the UI

### ISSUE THREAD

**Issue by piushan1992** [BlacklampsSE2/Game-Simulator#43]

**Comment by MadumalEkanayake** [comment]
![gameboard](https://user-images.githubusercontent.com/28650587/40889469-e26249f0-6784-11e8-9419-32f22041fa0e.jpg)
Company stocks list down with two buttons for each.

**Comment by Ruvimal1997** [comment]
I have added to buttons which will allow the player to buy or sell shares at his/her desire.
