### ISSUE TITLE
T1.2 Design a user Registration page

### ISSUE THREAD

**Issue by piushan1992** [BlacklampsSE2/Game-Simulator#9]

**Comment by MadumalEkanayake** [comment]
![register](https://user-images.githubusercontent.com/28650587/40889123-e9c07f10-677e-11e8-992f-b42534016a31.jpg)

This is the rough sketch for registration screen

**Comment by Ruvimal1997** [comment]
I have designed the UI using html, bootstrap, and CSS according to this rough sketch.
